//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HostingPlansPrice
    {
        public int ID { get; set; }
        public int HostingPlanID { get; set; }
        public int Months { get; set; }
        public decimal Price { get; set; }
    
        public virtual HostingPlan HostingPlan { get; set; }
    }
}
