//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HostingEntities : DbContext
    {
        public HostingEntities()
            : base("name=HostingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Feature> Features { get; set; }
        public virtual DbSet<HostingPlan> HostingPlans { get; set; }
        public virtual DbSet<HostingPlansPrice> HostingPlansPrices { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersHostingPlan> UsersHostingPlans { get; set; }
    }
}
